"""
Policy Tracking Storage
Simple JSON-based storage for policy status tracking
"""

import json
import os
from typing import List, Optional, Dict
from pathlib import Path
from datetime import datetime, timedelta

from backend.models.policy_status import PolicyTrackingItem, PolicyStatus, TimelineEvent, PolicyTrackingStats


class PolicyTracker:
    """Manage policy tracking data"""

    def __init__(self, storage_file: str = "./outputs/policy_tracking.json"):
        self.storage_file = storage_file
        self.ensure_storage_file()

    def ensure_storage_file(self):
        """Create storage file if it doesn't exist"""
        if not os.path.exists(self.storage_file):
            os.makedirs(os.path.dirname(self.storage_file), exist_ok=True)
            self.save_data({"policies": [], "stats": {}})

    def load_data(self) -> Dict:
        """Load tracking data from JSON file"""
        try:
            with open(self.storage_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        except:
            return {"policies": [], "stats": {}}

    def save_data(self, data: Dict):
        """Save tracking data to JSON file"""
        with open(self.storage_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    def create_policy_from_generation(self, policy_data: Dict, policy_id: str) -> PolicyTrackingItem:
        """Create tracking item from generated policy"""
        vulnerability = policy_data.get('vulnerability', {})
        policy = policy_data.get('policy', {})

        # Calculate due date based on severity
        severity = vulnerability.get('severity', 'medium').lower()
        days_map = {'critical': 2, 'high': 7, 'medium': 30, 'low': 90}
        days = days_map.get(severity, 30)
        due_date = (datetime.now() + timedelta(days=days)).isoformat()

        tracking_item = PolicyTrackingItem(
            policy_id=policy_id,
            vulnerability_title=vulnerability.get('title', 'Unknown'),
            vulnerability_type=vulnerability.get('type', 'sast'),
            severity=severity,
            status=PolicyStatus.NOT_STARTED,
            due_date=due_date,
            nist_csf_controls=policy.get('nist_csf_controls', []),
            iso27001_controls=policy.get('iso27001_controls', []),
            file_path=vulnerability.get('file_path') or vulnerability.get('url'),
            priority=policy.get('priority', 'medium'),
            timeline=[
                TimelineEvent(
                    event_type="created",
                    user="system",
                    details="Policy generated by SecurAI"
                )
            ]
        )

        return tracking_item

    def add_policies(self, policies: List[PolicyTrackingItem]):
        """Add multiple policies to tracking"""
        data = self.load_data()

        for policy in policies:
            data['policies'].append(policy.dict())

        self.update_stats(data)
        self.save_data(data)

    def get_all_policies(self) -> List[PolicyTrackingItem]:
        """Get all tracked policies"""
        data = self.load_data()
        return [PolicyTrackingItem(**p) for p in data.get('policies', [])]

    def get_policy(self, policy_id: str) -> Optional[PolicyTrackingItem]:
        """Get single policy by ID"""
        policies = self.get_all_policies()
        for policy in policies:
            if policy.policy_id == policy_id:
                return policy
        return None

    def update_policy_status(self, policy_id: str, new_status: PolicyStatus, user: str = None):
        """Update policy status"""
        data = self.load_data()

        for policy in data['policies']:
            if policy['policy_id'] == policy_id:
                old_status = policy['status']
                policy['status'] = new_status
                policy['updated_at'] = datetime.now().isoformat()

                # Add timeline event
                policy['timeline'].append({
                    "event_type": "status_changed",
                    "timestamp": datetime.now().isoformat(),
                    "user": user,
                    "from_status": old_status,
                    "to_status": new_status
                })

                break

        self.update_stats(data)
        self.save_data(data)

    def assign_policy(self, policy_id: str, assigned_to: str, user: str = None):
        """Assign policy to a user"""
        data = self.load_data()

        for policy in data['policies']:
            if policy['policy_id'] == policy_id:
                policy['assigned_to'] = assigned_to
                policy['updated_at'] = datetime.now().isoformat()

                policy['timeline'].append({
                    "event_type": "assigned",
                    "timestamp": datetime.now().isoformat(),
                    "user": user,
                    "details": f"Assigned to {assigned_to}"
                })

                break

        self.save_data(data)

    def update_stats(self, data: Dict):
        """Calculate and update statistics"""
        policies = data.get('policies', [])
        total = len(policies)

        if total == 0:
            data['stats'] = PolicyTrackingStats().dict()
            return

        status_counts = {}
        for policy in policies:
            status = policy.get('status', 'not_started')
            status_counts[status] = status_counts.get(status, 0) + 1

        # Calculate compliance (fixed + verified)
        completed = status_counts.get('fixed', 0) + status_counts.get('verified', 0)
        compliance_pct = (completed / total * 100) if total > 0 else 0

        data['stats'] = {
            "total_policies": total,
            "not_started": status_counts.get('not_started', 0),
            "in_progress": status_counts.get('in_progress', 0),
            "under_review": status_counts.get('under_review', 0),
            "fixed": status_counts.get('fixed', 0),
            "verified": status_counts.get('verified', 0),
            "reopened": status_counts.get('reopened', 0),
            "compliance_percentage": round(compliance_pct, 1)
        }

    def get_stats(self) -> PolicyTrackingStats:
        """Get current statistics"""
        data = self.load_data()
        return PolicyTrackingStats(**data.get('stats', {}))

    def get_dashboard_data(self) -> Dict:
        """Get all data for dashboard"""
        data = self.load_data()
        return {
            "policies": [PolicyTrackingItem(**p) for p in data.get('policies', [])],
            "stats": PolicyTrackingStats(**data.get('stats', {}))
        }
